# Generated by Django 6.0.2 on 2026-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='flightbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
